Update swapCreator.js
Modified functions 
[SwapCreator] Raydium SDK initialized
SwapCreator.js:224[DEBUG] Authority derivation failed: 
TypeError: Cannot read properties of undefined (reading 'getAssociatedAuthority') at SwapCreator.createPoolKeysFromTokenData (/Users/jose/Desktop/CodeV3/swapCreator.js:213:56) at SwapCreator.swapTokens (/Users/jose/Desktop/CodeV3/swapCreator.js:77:35) at process.processTicksAndRejections (node:internal/process/task_queues:105:5) at async Sniper.executeBuy (/Users/jose/Desktop/CodeV3/Sniper.js:50:13) at async SniperManager.addSniper (/Users/jose/Desktop/CodeV3/SniperManager.js:45:13) at async handleLog (/Users/jose/Desktop/CodeV3/newRaydiumLpListener.js:64:9) {stack: "TypeError: Cannot read properties of undefined (re…jose/Desktop/CodeV3/newRaydiumLpListener.js:64:9)", message: "Cannot read properties of undefined (reading 'getAssociatedAuthority')"}
SwapCreator.js:165[SwapCreator] Swap failed: 
TypeError: this.raydium.liquidity.refreshPools is not a function at SwapCreator.swapTokens (/Users/jose/Desktop/CodeV3/swapCreator.js:80:42) at process.processTicksAndRejections (node:internal/process/task_queues:105:5) at async Sniper.executeBuy (/Users/jose/Desktop/CodeV3/Sniper.js:50:13) at async SniperManager.addSniper (/Users/jose/Desktop/CodeV3/SniperManager.js:45:13) at async handleLog (/Users/jose/Desktop/CodeV3/newRaydiumLpListener.js:64:9) {stack: "TypeError: this.raydium.liquidity.refreshPools is …jose/Desktop/CodeV3/newRaydiumLpListener.js:64:9)", message: "this.raydium.liquidity.refreshPools is not a function"}
SwapCreator.js:277[DEBUG] Verifying token accounts:
SniperManager.js:49[SniperManager] addSniper error: this.raydium.liquidity.refreshPools is not a function
SwapCreator.js:283- Base ATA 5ND4TcSysp8u38rvvqLzS3kkwnNoSvUhuFpjVA68EnLc: MISSING
SwapCreator.js:290- Quote ATA 3j3iCi28839wYNgDCNBZNcxtjXSqL6sGHRJRWgx5GymX: MISSING
SwapCreator.js:297- Base Vault HUHMhKXz66dZpJa8eWuZeXHUwu8z71o5kdsevsqREUJ2: Exists